### ISSUE TITLE
Content Blocks and sync_crop_areas

### ISSUE THREAD

**Issue by Hobokens** [jweiland-net/sync_crop_areas#34]
I defined in my `content block`  in the `config.yaml` several cropvariants, following the extension `gallery-content`. 

```
    cropVariants:
      desktop:
        title: Desktop
        allowedAspectRatios:
          free:
            title: Free
            value: 0 / 0
          tv:
            title: TV (4:3)
            value: 4 / 3
          portrait:
            title: Portrait (3:4)
            value: 3 / 4
          square:
            title: Square (1:1)
            value: 1 / 1
          tower:
            title: Tower (9:16)
            value: 9 / 16
          skyscraper:
            title: Skyscraper (1:2.39)
            value: 1 / 2.39
          anamorphic:
            title: Anamorphic (2.39:1)
            value: 2.39 / 1
      tablet:
        title: Tablet
        allowedAspectRatios:
          free:
            title: Free
            value: 0 / 0
          tv:
            title: TV (4:3)
            value: 4 / 3
          portrait:
            title: Portrait (3:4)
            value: 3 / 4
          square:
            title: Square (1:1)
            value: 1 / 1
          tower:
            title: Tower (9:16)
            value: 9 / 16
          skyscraper:
            title: Skyscraper (1:2.39)
            value: 1 / 2.39
          anamorphic:
            title: Anamorphic (2.39:1)
            value: 2.39 / 1
      smartphone:
        title: Smartphone
        allowedAspectRatios:
          free:
            title: Free
            value: 0 / 0
          tv:
            title: TV (4:3)
            value: 4 / 3
          portrait:
            title: Portrait (3:4)
            value: 3 / 4
          square:
            title: Square (1:1)
            value: 1 / 1
          tower:
            title: Tower (9:16)
            value: 9 / 16
          skyscraper:
            title: Skyscraper (1:2.39)
            value: 1 / 2.39
          anamorphic:
            title: Anamorphic (2.39:1)
            value: 2.39 / 1
```
Is there a way to use `sync_crop_areas` for content blocks?
